

spring:
  datasource:
    url: jdbc:mysql://35.79.239.143:3306/jinniu?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: admin
    password: 0cf21ce35322d2e56d_%#745e319b933470
  flyway:
    locations: classpath:db/migration
    enabled: true


