spring:
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: test
    password: passwd
  dubbo:
    application:
      name: quant-monitor
    server: true
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20882
logging:
  level:
    root: info
    com.mzwise: debug
