server:
  port: 6606
  servlet:
    context-path: /points
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6600/eureka/
spring:
  application:
    name: points
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8